// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: proto/desktop.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadWebInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId int32  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Url       string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title     string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *UploadWebInfoRequest) Reset() {
	*x = UploadWebInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_desktop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadWebInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadWebInfoRequest) ProtoMessage() {}

func (x *UploadWebInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_desktop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadWebInfoRequest.ProtoReflect.Descriptor instead.
func (*UploadWebInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_desktop_proto_rawDescGZIP(), []int{0}
}

func (x *UploadWebInfoRequest) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *UploadWebInfoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadWebInfoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UploadWebInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UploadWebInfoResponse) Reset() {
	*x = UploadWebInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_desktop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadWebInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadWebInfoResponse) ProtoMessage() {}

func (x *UploadWebInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_desktop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadWebInfoResponse.ProtoReflect.Descriptor instead.
func (*UploadWebInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_desktop_proto_rawDescGZIP(), []int{1}
}

var File_proto_desktop_proto protoreflect.FileDescriptor

var file_proto_desktop_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x14,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x57, 0x65, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x57, 0x65, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x57, 0x0a, 0x07, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x12,
	0x4c, 0x0a, 0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x57, 0x65, 0x62, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x57,
	0x65, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x57, 0x65, 0x62, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_desktop_proto_rawDescOnce sync.Once
	file_proto_desktop_proto_rawDescData = file_proto_desktop_proto_rawDesc
)

func file_proto_desktop_proto_rawDescGZIP() []byte {
	file_proto_desktop_proto_rawDescOnce.Do(func() {
		file_proto_desktop_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_desktop_proto_rawDescData)
	})
	return file_proto_desktop_proto_rawDescData
}

var file_proto_desktop_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_desktop_proto_goTypes = []interface{}{
	(*UploadWebInfoRequest)(nil),  // 0: proto.UploadWebInfoRequest
	(*UploadWebInfoResponse)(nil), // 1: proto.UploadWebInfoResponse
}
var file_proto_desktop_proto_depIdxs = []int32{
	0, // 0: proto.Desktop.UploadWebInfo:input_type -> proto.UploadWebInfoRequest
	1, // 1: proto.Desktop.UploadWebInfo:output_type -> proto.UploadWebInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_desktop_proto_init() }
func file_proto_desktop_proto_init() {
	if File_proto_desktop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_desktop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadWebInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_desktop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadWebInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_desktop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_desktop_proto_goTypes,
		DependencyIndexes: file_proto_desktop_proto_depIdxs,
		MessageInfos:      file_proto_desktop_proto_msgTypes,
	}.Build()
	File_proto_desktop_proto = out.File
	file_proto_desktop_proto_rawDesc = nil
	file_proto_desktop_proto_goTypes = nil
	file_proto_desktop_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DesktopClient is the client API for Desktop service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DesktopClient interface {
	UploadWebInfo(ctx context.Context, in *UploadWebInfoRequest, opts ...grpc.CallOption) (*UploadWebInfoResponse, error)
}

type desktopClient struct {
	cc grpc.ClientConnInterface
}

func NewDesktopClient(cc grpc.ClientConnInterface) DesktopClient {
	return &desktopClient{cc}
}

func (c *desktopClient) UploadWebInfo(ctx context.Context, in *UploadWebInfoRequest, opts ...grpc.CallOption) (*UploadWebInfoResponse, error) {
	out := new(UploadWebInfoResponse)
	err := c.cc.Invoke(ctx, "/proto.Desktop/UploadWebInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DesktopServer is the server API for Desktop service.
type DesktopServer interface {
	UploadWebInfo(context.Context, *UploadWebInfoRequest) (*UploadWebInfoResponse, error)
}

// UnimplementedDesktopServer can be embedded to have forward compatible implementations.
type UnimplementedDesktopServer struct {
}

func (*UnimplementedDesktopServer) UploadWebInfo(context.Context, *UploadWebInfoRequest) (*UploadWebInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadWebInfo not implemented")
}

func RegisterDesktopServer(s *grpc.Server, srv DesktopServer) {
	s.RegisterService(&_Desktop_serviceDesc, srv)
}

func _Desktop_UploadWebInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadWebInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServer).UploadWebInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Desktop/UploadWebInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServer).UploadWebInfo(ctx, req.(*UploadWebInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Desktop_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Desktop",
	HandlerType: (*DesktopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadWebInfo",
			Handler:    _Desktop_UploadWebInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/desktop.proto",
}
