// Code generated by fyne-theme-generator

package theme

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/theme"
	"image/color"
)

var DarkTheme = darkTheme{
	t: theme.DarkTheme(),
}

type darkTheme struct {
	t fyne.Theme
}

func (d darkTheme) Color(c fyne.ThemeColorName, v fyne.ThemeVariant) color.Color {
	return d.t.Color(c, v)
}

func (d darkTheme) Font(s fyne.TextStyle) fyne.Resource {
	if s.Monospace {
		return fontMicrosoftYaHeiTtf
	}
	if s.Bold {
		if s.Italic {
			return fontMicrosoftYaHeiTtf
		}
		return fontMicrosoftYaHeiTtf
	}
	if s.Italic {
		return fontMicrosoftYaHeiTtf
	}
	return fontMicrosoftYaHeiTtf
}

func (d darkTheme) Icon(n fyne.ThemeIconName) fyne.Resource {
	return d.t.Icon(n)
}

func (d darkTheme) Size(s fyne.ThemeSizeName) float32 {
	return d.t.Size(s)
}
