// Code generated by fyne-theme-generator

package theme

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/theme"
	"image/color"
)

var LightTheme = lightTheme{
	t: theme.LightTheme(),
}

type lightTheme struct {
	t fyne.Theme
}

func (l lightTheme) Color(c fyne.ThemeColorName, v fyne.ThemeVariant) color.Color {
	return l.t.Color(c, v)
}

func (lightTheme) Font(s fyne.TextStyle) fyne.Resource {
	if s.Monospace {
		return fontMicrosoftYaHeiTtf
	}
	if s.Bold {
		if s.Italic {
			return fontMicrosoftYaHeiTtf
		}
		return fontMicrosoftYaHeiTtf
	}
	if s.Italic {
		return fontMicrosoftYaHeiTtf
	}
	return fontMicrosoftYaHeiTtf
}

func (l lightTheme) Icon(n fyne.ThemeIconName) fyne.Resource {
	return l.t.Icon(n)
}

func (l lightTheme) Size(s fyne.ThemeSizeName) float32 {
	return l.t.Size(s)
}
