package theme

const (
	AppTitle   = "Sid Desktop"
	WelComeMsg = "Welcome to Sid Desktop"

	// QuitAppTitle begins for common messages
	QuitAppTitle = "Want To Quit?"
	QuitAppMsg   = "Are you sure to want to quit?"

	DismissText = "Cancel"
	ConfirmText = "OK"

	CannotCloseTitle = "Cannot Close"

	AppPageRefresh = "Refresh"
	AppPageMetrics = "Metrics"

	WebPageProcessErrorFormat = "process webpage failed. %v"
	NetWorkErrorFormat        = "network error. %v"
	InvalidContentFormat      = "invalid content. %v"
	InternalErrorFormat       = "there is a internal error: %v"

	TextCursorPosFormat = "Row:%d Col:%d"

	// AppWelcomeName begins for built-in apps
	AppWelcomeName = "WelCome"

	AppLauncherName                      = "App Launcher"
	AppLauncherSearchPlaceHolder         = "Type the name of application or `enter` to run directly"
	AppLauncherExplorerText              = "Explorer"
	AppLauncherExplorerSidPathName       = "Sid Desktop Path"
	AppLauncherConfigBtnText             = "Config"
	AppLauncherCannotCloseMsg            = "Config Window is running now. Close it first, please"
	AppLauncherAppListHeader1            = "AppIcon/Name"
	AppLauncherAppListHeader2            = "Last Access Time"
	AppLauncherAppListOp1                = "Open File Location"
	AppLauncherAppListOp2                = "Run"
	AppLauncherNeedInitTitle             = "Need Init Index"
	AppLauncherNeedInitMsg               = "App index is not built, want to initialize the index?"
	AppLauncherConfigTitle               = AppLauncherName + "-" + AppLauncherConfigBtnText
	AppLauncherConfigAddDirBtn           = "Add Dir"
	AppLauncherConfigRmDirBtn            = "Remove"
	AppLauncherConfigFileFilter          = "File Mask:"
	AppLauncherConfigBuildBtn            = "Build"
	AppLauncherConfigIndexBuilding       = "Index is building"
	AppLauncherConfigStartScanApp        = "Begin to scan app..."
	AppLauncherConfigFinishScanAppFormat = "Scan App finished. Found %d apps"
	AppLauncherConfigCannotCloseMsg      = "Index is building. Cannot close"
	OpenAppLocationFailedFormat          = "open location for %s failed. %v"
	RunAppFailedFormat                   = "run %s failed. %v"
	UpdateAppIndexFailedFormat           = "update index for %s failed. %v"
	RunCommandFailedFormat               = "run command %s failed. %v"
	RunExplorerFailedFormat              = "run explorer to %s failed. %v"
	RunAppIndexFailedFormat              = "app index run failed. %v"

	AppFavoritesName                   = "Favorites"
	AppFavoritesSearchText             = "Type the name, url or tags of favorites"
	AppFavoritesImportBtnText          = "Import"
	AppFavoritesExportBtnText          = "Export"
	AppFavoritesAddFavorBtnText        = "Add"
	AppFavoritesRmFavorBtnText         = "Remove"
	AppFavoritesFavorListOp1           = "Edit"
	AppFavoritesFavorListOp2           = "Open"
	AppFavoritesFavorListHeader1       = "Name(Tags)"
	AppFavoritesFavorListHeader2       = "Url"
	AppFavoritesAddFavorTitle          = "Add Favor"
	AppFavoritesEditFavorTitle         = "Edit Favor"
	AppFavoritesAddFavorName           = "Name"
	AppFavoritesAddFavorUrl            = "Url"
	AppFavoritesAddFavorUrlPlaceHolder = "Start with 'http(s)://', type `enter` to get title"
	AppFavoritesAddFavorTags           = "Tags"
	AppFavoritesAddFavorExpand         = "Expand"
	AppFavoritesAddFavorShrink         = "Shrink"
	ProcessFavoritesFailedFormat       = "process favorites failed. %v"
	OpenFavoritesFailedFormat          = "open favorites failed. %v"
	ExportFavoritesFailedFormat        = "export favorites failed. %v"
	ImportFavoritesFailedFormat        = "import favorites failed. %v"

	AppScriptRunnerName                  = "Script Runner"
	AppScriptRunnerNewScript             = "New"
	AppScriptRunnerSaveScript            = "Save"
	AppScriptRunnerRunScript             = "Run"
	AppScriptRunnerStopScript            = "Stop"
	AppScriptRunnerDelScript             = "Del"
	AppScriptRunnerCurScriptName         = "Script Name"
	AppScriptRunnerClearLog              = "Clear Log"
	ProcessScriptRunnerFailedFormat      = "process script runner failed. %v"
	AppScriptRunnerNewScriptName         = "New Script Name"
	AppScriptRunnerCannotCloseMsg        = "Script is running now. Wait it stop or stop it, please"
	AppScriptRunnerScriptNameValidateMsg = AppScriptRunnerCurScriptName + " must not be empty"

	AppDevToolsName                           = "Dev Tools"
	AppDevToolsFailedFormat                   = "process app dev tools failed. %v"
	AppDevToolsTextProcName                   = "Text Process"
	AppDevToolsJsonProcName                   = "Json"
	AppDevToolsCompressJsonName               = "Compress"
	AppDevToolsPrettyJsonName                 = "Pretty"
	AppDevToolsBase64ProcName                 = "Base64"
	AppDevToolsBase64EncodeName               = "Encode"
	AppDevToolsBase64DecodeName               = "Decode"
	AppDevToolsBase64UrlModeName              = "URL/FileName"
	AppDevToolsBase64FillModeName             = "Fill With '='"
	AppDevToolsBase64InputName                = "input"
	AppDevToolsBase64OutputName               = "output"
	AppDevToolsDateTimeName                   = "DateTime"
	AppDevToolsDateTimeTSUnit                 = "TimeStamp Unit"
	AppDevToolsDateTimeDTFormat               = "DateTime Format"
	AppDevToolsDateTimeFromTsToDtTitle        = "From Timestamp to DateTime"
	AppDevToolsDateTimeFromDtToTsTitle        = "From DateTime to Timestamp"
	AppDevToolsDateTimeNowTSName              = "Now Timestamp"
	AppDevToolsDateTimeNowDateTimeName        = "Now DateTime"
	AppDevToolsDateTimeTimeStampName          = "Timestamp"
	AppDevToolsDateTimeDateTimeName           = "DateTime"
	AppDevToolsDateTimeStartBtnName           = "Start"
	AppDevToolsDateTimeStopBtnName            = "Stop"
	AppDevToolsDateTimeConvertBtnName         = "Convert"
	AppDevToolsCliName                        = "Client"
	AppDevToolsHttpCliName                    = "Http Client"
	AppDevToolsHttpCliMethodPlaceHolder       = "Method"
	AppDevToolsHttpCliUrlPlaceHolder          = "Url"
	AppDevToolsHttpCliUrlValidateMsg          = AppDevToolsHttpCliUrlPlaceHolder + " must not be empty"
	AppDevToolsHttpCliReqHeaderKeyPlaceHolder = "key"
	AppDevToolsHttpCliReqHeaderValPlaceHolder = "value"
	AppDevToolsHttpCliSendReqName             = "Send"
	AppDevToolsHttpCliSearchHisName           = "Search History"
	AppDevToolsHttpCliRmReqHeaderName         = "Remove"
	AppDevToolsHttpCliBodyTypeName1           = "None"
	AppDevToolsHttpCliBodyTypeName2           = "Json"
	AppDevToolsHttpCliHeaderTabName           = "Header"
	AppDevToolsHttpCliBodyTabName             = "Body"
	AppDevToolsHttpCliAuthTabName             = "Authorization"
	AppDevToolsHttpCliAuthTypeName1           = "No Auth"
	AppDevToolsHttpCliAuthTypeName2           = "Basic Auth"
	AppDevToolsHttpCliBasicAuthUser           = "Username"
	AppDevToolsHttpCliBasicAuthPass           = "Password"
	AppDevToolsCliPrettyJsonName              = "Pretty"
	AppDevToolsCliRespStatusFormat            = "Status: %s Time: %v Size: %d"
	AppDevToolsCliPreviewTitle                = "Preview"
	AppDevToolsCliSearchTitle                 = AppDevToolsHttpCliName + "-" + AppDevToolsHttpCliSearchHisName
	AppDevToolsCliPreviewLoading              = "History is loading ..."
	AppDevToolsCliPreviewSearchPlaceHolder    = "Search for method/url"

	AppSodorName                             = "Sodor"
	AppSodorJobTabName                       = "Jobs"
	AppSodorJobListName                      = "Job List"
	AppSodorCreateJob                        = "New Job"
	AppSodorJobSearchText                    = "Type the name of jobs"
	AppSodorJobListHeader1                   = "ID"
	AppSodorJobListHeader2                   = "Name"
	AppSodorJobListHeader3                   = "CreateTime"
	AppSodorJobListHeader4                   = "UpdateTime"
	AppSodorJobListOp1                       = "Edit"
	AppSodorJobListOp2                       = "View Instance"
	AppSodorJobListOp3                       = "Del"
	AppSodorJobInfoTitle                     = "Job"
	AppSodorJobInfoJobID                     = "ID"
	AppSodorJobInfoJobName                   = "Name"
	AppSodorJobInfoJobScheduleMode           = "ScheduleMode"
	AppSodorJobInfoJobAlertGroup             = "AlertGroup"
	AppSodorJobInfoTaskTitle                 = "Task"
	AppSodorJobInfoAddTask                   = "Add Task"
	AppSodorTaskListOp1                      = "Del"
	AppSodorJobInfoTaskID                    = "ID"
	AppSodorJobInfoTaskName                  = "Name"
	AppSodorJobInfoTaskType                  = "Type"
	AppSodorJobInfoRunningHost               = "Running Host"
	AppSodorJobInfoTaskContent               = "Content"
	AppSodorJobInfoRelationTitle             = "Task Relation"
	AppSodorJobInfoAddTaskRelation           = "Add Relation"
	AppSodorRelationItemOp1                  = "Del"
	AppSodorRelationItemDirection            = " => "
	AppSodorJobInfoJobInstance               = "Job Instance"
	AppSodorJobInfoJobInstanceID             = "ID"
	AppSodorJobInfoJobInstanceScheduleTime   = "Schedule Time"
	AppSodorJobInfoJobInstanceStartTime      = "Start Time"
	AppSodorJobInfoJobInstanceStopTime       = "Stop Time"
	AppSodorJobInfoJobInstanceExitCode       = "Exit Code"
	AppSodorJobInfoJobInstanceExitMsg        = "Exit Msg"
	AppSodorJobInfoTaskInstance              = "Task Instance"
	AppSodorJobInfoTaskInstanceJobInsID      = "Job Instance ID"
	AppSodorJobInfoTaskInstanceID            = "ID"
	AppSodorJobInfoTaskInstanceTaskName      = "TaskName"
	AppSodorJobInfoTaskInstanceStartTime     = "Start Time"
	AppSodorJobInfoTaskInstanceStopTime      = "Stop Time"
	AppSodorJobInfoTaskInstanceRunHost       = "Host"
	AppSodorJobInfoTaskInstancePID           = "PID"
	AppSodorJobInfoTaskInstanceExitCode      = "Exit Code"
	AppSodorJobInfoTaskInstanceExitMsg       = "Exit Msg"
	AppSodorJobInfoTaskInstanceParsedContent = "Parsed Content"
	AppSodorJobInfoTaskInstanceOutputVars    = "Output Vars"
	AppSodorJobInfoTaskInstanceListOp1       = "Detail"

	AppSodorThomasListName               = "Thomas List"
	AppSodorThomasSearchText             = "Type the name of thomas"
	AppSodorAddThomas                    = "Add Thomas"
	AppSodorEditThomas                   = "Edit Thomas"
	AppSodorThomasInfo                   = "Thomas Info"
	AppSodorThomasInfoID                 = "ID"
	AppSodorThomasInfoVersion            = "Version"
	AppSodorThomasInfoHost               = "Host"
	AppSodorThomasInfoPort               = "Port"
	AppSodorThomasInfoHostPort           = "Host:Port"
	AppSodorThomasInfoTags               = "Tags"
	AppSodorThomasInfoPID                = "PID"
	AppSodorThomasInfoStatus             = "Status"
	AppSodorThomasInfoName               = "Name"
	AppSodorThomasInfoProto              = "Proto"
	AppSodorThomasInfoStartTime          = "Start Time"
	AppSodorThomasInfoHeartBeatTime      = "Heart Beat Time"
	AppSodorThomasInfoType               = "Type"
	AppSodorThomasListOp1                = "View Instance"
	AppSodorThomasListOp2                = "Edit"
	AppSodorThomasListOp3                = "Del"
	AppSodorThomasAddThomasExpand        = "Expand"
	AppSodorThomasAddThomasShrink        = "Shrink"
	AppSodorThomasInfoInstance           = "Instance"
	AppSodorThomasInfoInstanceID         = "ID"
	AppSodorThomasInfoInstanceCreateTime = "Create Time"
	AppSodorThomasInfoInstanceMetrics    = "Metrics"

	AppSodorAddAlertGroup              = "Add Alert Group"
	AppSodorCreateAlertGroupID         = "ID"
	AppSodorCreateAlertGroupName       = "Name"
	AppSodorCreateAlertGroupPlugins    = "Plugin Instance"
	AppSodorCreateAlertGroupCreateTime = "CreateTime"
	AppSodorCreateAlertGroupUpdateTime = "UpdateTime"
	AppSodorCreateAlertGroupOp1        = "Edit"
	AppSodorCreateAlertGroupOp2        = "Alert History"
	AppSodorCreateAlertGroupOp3        = "Del"

	AppSodorAddAlertGroupHistory            = "Alert Group History"
	AppSodorCreateAlertGroupPluginID        = "Plugin Instance ID"
	AppSodorCreateAlertGroupPluginName      = "Plugin Instance Name"
	AppSodorCreateAlertGroupAlertMsg        = "Alert Message"
	AppSodorCreateAlertGroupStatusMsg       = "Status"
	AppSodorCreateAlertGroupAlertCreateTime = "CreateTime"

	AppSodorCreateAlertPluginInstance           = "New Alert Plugin Instance"
	AppSodorCreateAlertPluginInstanceID         = "ID"
	AppSodorCreateAlertPluginInstanceName       = "Name"
	AppSodorCreateAlertPluginInstancePlugin     = "Plugin Name"
	AppSodorCreateAlertPluginInstanceCreateTime = "CreateTime"
	AppSodorCreateAlertPluginInstanceUpdateTime = "UpdateTime"
	AppSodorCreateAlertPluginOp1                = "Edit"
	AppSodorCreateAlertPluginOp2                = "Del"
	AppSodorCreateAlertPluginDingDing           = "DingDing"
	AppSodorCreateAlertPluginDingDingWebHook    = "WebHook"
	AppSodorCreateAlertPluginDingDingSign       = "Sign"
	AppSodorCreateAlertPluginDingDingAtMobiles  = "AtMobiles"

	AppSodorFatCtlSetAddr         = "Set Addr of Fat Controller"
	AppSodorFatCtlAddr            = "Addr of Fat Controller"
	AppSodorFatCtlAddrValidateMsg = AppSodorFatCtlAddr + " must not be empty"
	AppSodorFatCtlAddrPlaceHolder = "The Addr($host:$port) of the fat controller"
	ProcessSodorFailedFormat      = "process sodor failed. %v"
	AppSodorInitFatCtlAddrMessage = "Please Set the FatCtrl Addr first"

	AppSodorJobListCannotCloseMsg        = "The job list can NOT be closed. :)"
	AppSodorThomasListCannotCloseMsg     = "The thomas list can NOT be closed. :)"
	AppSodorAlertGroupListCannotCloseMsg = "The alert group list can NOT be closed. :)"
	AppSodorThomsTabName                 = "Thomas"
	AppSodorFatCtrlTabName               = "Fat Controller"
	AppSodorAlertGroupTabName            = "Alert Groups"
	AppSodorAlertPluginTabName           = "Alert Plugins"

	LogViewerRefreshBtn = "Refresh"
	LogViewerTitle      = "Show Log"

	AboutTitle = "About"
	AboutIntro = `
## Sid Desktop  

Sid desktop is a desktop software based on [Fyne](https://fyne.io/),  

which is purely built by personal interests.  

The Source code is [sid-desktop](https://github.com/BabySid/sid-desktop).  

`

	// MenuSys begins for menus
	MenuSys     = "System"
	MenuSysQuit = "Quit"

	MenuOption          = "Option"
	MenuOptTheme        = "Theme"
	MenuOptThemeDark    = "Dark"
	MenuOptThemeLight   = "Light"
	MenuOptFullScreen   = "FullScreen"
	MenuOptHideWhenQuit = "Hide When Quit"

	MenuHelp      = "Help"
	MenuHelpLog   = "Show Log"
	MenuHelpAbout = "About Sid"

	// ToyDateTimeTitle begins for toys
	ToyDateTimeTitle               = "DateTime"
	ToyResourceMonitorTitle        = "Monitor"
	ToyResourceMonitorItem1        = "CPU:"
	ToyResourceMonitorItem2        = "MEM:"
	ToyResourceMonitorUpTimeFormat = "Up time %d:%d:%d"
	ToyHotSearchTitle              = "Hot Search(BD)"
	ToyHotSearchRefreshing         = "Content is Updating"
	ToyHotSearchRefreshFormat      = "Refresh (%d/%d)"
	ToyHotSearchUpdateComplete     = "hot search update complete"

	// SysTrayMenuQuitTooltip begins for systray
	SysTrayMenuQuitTooltip = "Quit Window"
	SysTrayMenuShow        = "Show"
	SysTrayMenuShowTooltip = "Show Window"
	SysTrayMenuHide        = "Hide"
	SysTrayMenuHideTooltip = "Hide Window"
)
