package theme

const (
	AppTitle   = "Sid Desktop"
	WelComeMsg = "Welcome to Sid Desktop"

	// QuitAppTitle begins for common messages
	QuitAppTitle = "Want To Quit?"
	QuitAppMsg   = "Are you sure to want to quit?"

	DismissText = "Cancel"
	ConfirmText = "OK"

	CannotCloseTitle = "Cannot Close"

	WebPageProcessErrorFormat = "process webpage failed. %s"
	NetWorkErrorFormat        = "network error. %s"
	InvalidContentFormat      = "invalid content. %s"
	InternalErrorFormat       = "there is a internal error: %s"

	TextCursorPosFormat = "Row:%d Col:%d"

	// AppWelcomeName begins for built-in apps
	AppWelcomeName = "WelCome"

	AppLauncherName                      = "App Launcher"
	AppLauncherSearchPlaceHolder         = "Type the name of application or `enter` to run directly"
	AppLauncherExplorerText              = "Explorer"
	AppLauncherConfigBtnText             = "Config"
	AppLauncherCannotCloseMsg            = "Config Window is running now. Close it first, please"
	AppLauncherAppListHeader1            = "AppIcon/Name"
	AppLauncherAppListHeader2            = "Last Access Time"
	AppLauncherAppListOp1                = "Open File Location"
	AppLauncherAppListOp2                = "Run"
	AppLauncherNeedInitTitle             = "Need Init Index"
	AppLauncherNeedInitMsg               = "App index is not built, want to initialize the index?"
	AppLauncherConfigTitle               = AppLauncherName + "-" + AppLauncherConfigBtnText
	AppLauncherConfigAddDirBtn           = "Add Dir"
	AppLauncherConfigRmDirBtn            = "Remove"
	AppLauncherConfigFileFilter          = "File Mask:"
	AppLauncherConfigBuildBtn            = "Build"
	AppLauncherConfigIndexBuilding       = "Index is building"
	AppLauncherConfigStartScanApp        = "Begin to scan app..."
	AppLauncherConfigFinishScanAppFormat = "Scan App finished. Found %d apps"
	AppLauncherConfigCannotCloseMsg      = "Index is building. Cannot close"
	OpenAppLocationFailedFormat          = "open location for %s failed. %s"
	RunAppFailedFormat                   = "run %s failed. %s"
	UpdateAppIndexFailedFormat           = "update index for %s failed. %s"
	RunCommandFailedFormat               = "run command %s failed. %s"
	RunExplorerFailedFormat              = "run explorer to %s failed. %s"
	RunAppIndexFailedFormat              = "app index run failed. %s"

	AppFavoritesName                   = "Favorites"
	AppFavoritesSearchText             = "Type the name, url or tags of favorites"
	AppFavoritesImportBtnText          = "Import"
	AppFavoritesExportBtnText          = "Export"
	AppFavoritesAddFavorBtnText        = "Add"
	AppFavoritesRmFavorBtnText         = "Remove"
	AppFavoritesFavorListOp1           = "Edit"
	AppFavoritesFavorListOp2           = "Open"
	AppFavoritesFavorListHeader1       = "Name(Tags)"
	AppFavoritesFavorListHeader2       = "Url"
	AppFavoritesAddFavorTitle          = "Add Favor"
	AppFavoritesAddFavorName           = "Name"
	AppFavoritesAddFavorUrl            = "Url"
	AppFavoritesAddFavorUrlPlaceHolder = "Start with 'http(s)://', type `enter` to get title"
	AppFavoritesAddFavorTags           = "Tags"
	AppFavoritesAddFavorExpand         = "Expand"
	AppFavoritesAddFavorShrink         = "Shrink"
	ProcessFavoritesFailedFormat       = "process favorites failed. %s"
	OpenFavoritesFailedFormat          = "open favorites failed. %s"
	ExportFavoritesFailedFormat        = "export favorites failed. %s"
	ImportFavoritesFailedFormat        = "import favorites failed. %s"

	AppScriptRunnerName                  = "Script Runner"
	AppScriptRunnerNewScript             = "New"
	AppScriptRunnerSaveScript            = "Save"
	AppScriptRunnerRunScript             = "Run"
	AppScriptRunnerStopScript            = "Stop"
	AppScriptRunnerDelScript             = "Del"
	AppScriptRunnerCurScriptName         = "Script Name"
	AppScriptRunnerClearLog              = "Clear Log"
	ProcessScriptRunnerFailedFormat      = "process script runner failed. %s"
	AppScriptRunnerNewScriptName         = "New Script Name"
	AppScriptRunnerCannotCloseMsg        = "Script is running now. Wait it stop or stop it, please"
	AppScriptRunnerScriptNameValidateMsg = AppScriptRunnerCurScriptName + " must not be empty"

	AppDevToolsName                           = "Dev Tools"
	AppDevToolsTextProcName                   = "Text Process"
	AppDevToolsJsonProcName                   = "Json"
	AppDevToolsCompressJsonName               = "Compress"
	AppDevToolsPrettyJsonName                 = "Pretty"
	AppDevToolsBase64ProcName                 = "Base64"
	AppDevToolsBase64EncodeName               = "Encode"
	AppDevToolsBase64DecodeName               = "Decode"
	AppDevToolsBase64UrlModeName              = "URL/FileName"
	AppDevToolsBase64FillModeName             = "Fill With '='"
	AppDevToolsBase64InputName                = "input"
	AppDevToolsBase64OutputName               = "output"
	AppDevToolsDateTimeName                   = "DateTime"
	AppDevToolsDateTimeTSUnit                 = "TimeStamp Unit"
	AppDevToolsDateTimeDTFormat               = "DateTime Format"
	AppDevToolsDateTimeFromTsToDtTitle        = "From Timestamp to DateTime"
	AppDevToolsDateTimeFromDtToTsTitle        = "From DateTime to Timestamp"
	AppDevToolsDateTimeNowTSName              = "Now Timestamp"
	AppDevToolsDateTimeNowDateTimeName        = "Now DateTime"
	AppDevToolsDateTimeTimeStampName          = "Timestamp"
	AppDevToolsDateTimeDateTimeName           = "DateTime"
	AppDevToolsDateTimeStartBtnName           = "Start"
	AppDevToolsDateTimeStopBtnName            = "Stop"
	AppDevToolsDateTimeConvertBtnName         = "Convert"
	AppDevToolsCliName                        = "Client"
	AppDevToolsHttpCliName                    = "Http Client"
	AppDevToolsHttpCliUrlPlaceHolder          = "url"
	AppDevToolsHttpCliReqHeaderKeyPlaceHolder = "key"
	AppDevToolsHttpCliReqHeaderValPlaceHolder = "value"
	AppDevToolsHttpCliSendReqName             = "Send"
	AppDevToolsHttpCliSearchHisName           = "Search History"
	AppDevToolsHttpCliRmReqHeaderName         = "Remove"
	AppDevToolsHttpCliBodyTypeName1           = "None"
	AppDevToolsHttpCliBodyTypeName2           = "Json"
	AppDevToolsHttpCliHeaderTabName           = "Header"
	AppDevToolsHttpCliBodyTabName             = "Body"
	AppDevToolsHttpCliAuthTabName             = "Authorization"
	AppDevToolsHttpCliAuthTypeName1           = "No Auth"
	AppDevToolsHttpCliAuthTypeName2           = "Basic Auth"
	AppDevToolsHttpCliBasicAuthUser           = "Username"
	AppDevToolsHttpCliBasicAuthPass           = "Password"
	AppDevToolsCliPrettyJsonName              = "Pretty"
	AppDevToolsCliRespStatusFormat            = "Status: %s Time: %v Size: %d"

	LogViewerRefreshBtn = "Refresh"
	LogViewerTitle      = "Show Log"

	AboutTitle = "About"
	AboutIntro = `## Sid Desktop  

Sid desktop is a desktop software based on [Fyne](https://fyne.io/),  

which is purely built by personal interests.

The Source code is [sid-desttop](https://github.com/BabySid/sid-desktop).`

	// MenuSys begins for menus
	MenuSys     = "System"
	MenuSysQuit = "Quit"

	MenuOption        = "Option"
	MenuOptTheme      = "Theme"
	MenuOptThemeDark  = "Dark"
	MenuOptThemeLight = "Light"
	MenuOptFullScreen = "FullScreen"

	MenuHelp      = "Help"
	MenuHelpLog   = "Show Log"
	MenuHelpAbout = "About Sid"

	// ToyDateTimeTitle begins for toys
	ToyDateTimeTitle               = "DateTime"
	ToyResourceMonitorTitle        = "Monitor"
	ToyResourceMonitorItem1        = "CPU:"
	ToyResourceMonitorItem2        = "MEM:"
	ToyResourceMonitorUpTimeFormat = "Up time %d:%d:%d"
	ToyHotSearchTitle              = "Hot Search(BD)"
	ToyHotSearchRefreshing         = "Content is Updating"
	ToyHotSearchRefreshFormat      = "Refresh (%d/%d)"
	ToyHotSearchUpdateComplete     = "hot search update complete"
)
